# Generated by Django 4.2 on 2023-04-11 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('date_created_poll', models.DateTimeField(auto_created=True)),
                ('id_poll', models.UUIDField(primary_key=True, serialize=False)),
                ('name_poll', models.TextField(max_length=200)),
                ('description_poll', models.TextField(max_length=500)),
                ('objetive_poll', models.TextField(max_length=500)),
                ('date_updated_poll', models.DateTimeField(auto_now=True)),
                ('active_poll', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionConfiguration',
            fields=[
                ('id_question_configuration', models.UUIDField(primary_key=True, serialize=False)),
                ('label_question_configuration', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeQuestion',
            fields=[
                ('id_type_question', models.UUIDField(primary_key=True, serialize=False)),
                ('name_type_question', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id_question', models.UUIDField(primary_key=True, serialize=False)),
                ('title_question', models.TextField(max_length=300)),
                ('poll_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.polls')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOptions',
            fields=[
                ('id_question_options', models.UUIDField(primary_key=True, serialize=False)),
                ('name_question_options', models.TextField(max_length=100)),
                ('value_question_options', models.TextField(max_length=50)),
                ('label_question_options', models.TextField(max_length=50)),
                ('question_configuration_options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.questionconfiguration')),
            ],
        ),
        migrations.AddField(
            model_name='questionconfiguration',
            name='question_configuration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='encuestas.questions'),
        ),
        migrations.AddField(
            model_name='questionconfiguration',
            name='type_question_configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.typequestion'),
        ),
    ]
