# Generated by Django 4.2 on 2023-05-28 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('date_created_answer', models.DateTimeField(auto_created=True)),
                ('id_answer', models.AutoField(primary_key=True, serialize=False)),
                ('token_answer', models.TextField(max_length=255)),
                ('birth_date_answer', models.DateField(null=True)),
                ('genre_answer', models.TextField(max_length=1, null=True)),
                ('email_answer', models.TextField(max_length=50, null=True)),
                ('name_answer', models.TextField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id_permission', models.AutoField(primary_key=True, serialize=False)),
                ('name_permission', models.TextField(max_length=50)),
                ('description_permission', models.TextField(max_length=250)),
                ('active_permission', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id_person', models.AutoField(primary_key=True, serialize=False)),
                ('name_person', models.TextField(max_length=50)),
                ('birth_date_person', models.DateField()),
                ('img_person', models.TextField(max_length=250, null=True)),
                ('email_person', models.TextField(max_length=50)),
                ('genre_person', models.TextField(max_length=1)),
                ('active_person', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('date_created_poll', models.DateTimeField(auto_created=True)),
                ('id_poll', models.AutoField(primary_key=True, serialize=False)),
                ('title_poll', models.TextField(max_length=200)),
                ('object_poll', models.TextField(max_length=500)),
                ('description_poll', models.TextField(max_length=500)),
                ('instructions_poll', models.TextField(max_length=500)),
                ('date_start_poll', models.DateTimeField()),
                ('date_end_poll', models.DateTimeField()),
                ('token_poll', models.TextField(max_length=255, unique=True)),
                ('limit_sample_poll', models.IntegerField(default=10000)),
                ('user_poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.persons')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('name_rol', models.TextField(max_length=50)),
                ('description_rol', models.TextField(max_length=250)),
                ('active_rol', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeQuestion',
            fields=[
                ('id_type_question', models.AutoField(primary_key=True, serialize=False)),
                ('name_type_question', models.TextField(max_length=50)),
                ('description_type_question', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('username_user', models.TextField(max_length=50)),
                ('password_user', models.TextField(max_length=255)),
                ('token_user', models.TextField(max_length=255, null=True)),
                ('fails_login_user', models.IntegerField(default=0)),
                ('active_person', models.BooleanField(default=True)),
                ('person_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.persons')),
            ],
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id_user_rol', models.AutoField(primary_key=True, serialize=False)),
                ('rol_user_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.roles')),
                ('user_user_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.users')),
            ],
        ),
        migrations.CreateModel(
            name='RolPermissions',
            fields=[
                ('id_rol_permission', models.AutoField(primary_key=True, serialize=False)),
                ('permission_rol_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.permissions')),
                ('rol_rol_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id_question', models.AutoField(primary_key=True, serialize=False)),
                ('title_question', models.TextField(max_length=300)),
                ('poll_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.polls')),
                ('type_question_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.typequestion')),
            ],
        ),
        migrations.CreateModel(
            name='OptionsQuestion',
            fields=[
                ('id_option_question', models.AutoField(primary_key=True, serialize=False)),
                ('title_option_question', models.TextField(max_length=250)),
                ('name_option_question', models.TextField(max_length=50)),
                ('description_option_question', models.TextField(max_length=250, null=True)),
                ('value_option_question', models.TextField(default='')),
                ('id_option', models.TextField(max_length=100, null=True)),
                ('order_option_question', models.IntegerField(default=0, null=True)),
                ('question_option_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.questions')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryPassword',
            fields=[
                ('date_created_history_password', models.DateTimeField(auto_created=True)),
                ('id_history_password', models.AutoField(primary_key=True, serialize=False)),
                ('password_history_password', models.TextField(max_length=255)),
                ('user_history_password', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.users')),
            ],
        ),
        migrations.CreateModel(
            name='AnswersQuestions',
            fields=[
                ('date_created_answer_question', models.DateTimeField(auto_created=True)),
                ('id_answer_question', models.AutoField(primary_key=True, serialize=False)),
                ('value_answer_question', models.IntegerField(default=0, null=True)),
                ('text_answer_question', models.TextField(max_length=500, null=True)),
                ('token_answer_question', models.TextField(max_length=255, null=True)),
                ('answer_answer_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.answers')),
                ('option_answer_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='encuestas.optionsquestion')),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='poll_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.polls'),
        ),
    ]
