# Generated by Django 4.2 on 2023-04-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='id_poll',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='questionconfiguration',
            name='id_question_configuration',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='questionoptions',
            name='id_question_options',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='questions',
            name='id_question',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typequestion',
            name='id_type_question',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
